523 Email confirmation
devsummit/backend pull request #524
Opened 2017-10-18 14:38 UTC by aditiapratama1231

#523 

### Breakdown:
- [x] Create confirmed field
- [x] check if user not confirmed they can't logged in
- [x] except admin

### Screenshot:
table user who have confirmed
![user confirm](https://user-images.githubusercontent.com/21031005/31724619-73b1e268-b44c-11e7-95d1-e6c0abe44249.png)

if logged in as user with no have confirmed
![not confirm](https://user-images.githubusercontent.com/21031005/31724648-86d76f3e-b44c-11e7-9cd2-532acfe3b114.png)

if logged in as user with have confirmed
![confirm](https://user-images.githubusercontent.com/21031005/31724673-935f4dd0-b44c-11e7-8922-830298f5ace4.png)

if logged in as admin, note : admin doesn't have confirmed, and they can logged in
![admin confirm](https://user-images.githubusercontent.com/21031005/31724710-aaff3efa-b44c-11e7-9e16-84625d6deca9.png)

2017-10-18 17:02 UTC, andy-shi88 requested changes

2017-10-18 17:02 UTC, andy-shi88 commented on app/controllers/user_authorization_controller.py
> +                        if user.as_dict()['confirmed'] is not None or user.as_dict()['role_id'] == 1:
I think we can simplify this without using as_dict() here, just use user.confirmed should do.

2017-10-18 17:08 UTC, aditiapratama1231 commented on app/controllers/user_authorization_controller.py
> +                        if user.as_dict()['confirmed'] is not None or user.as_dict()['role_id'] == 1:
okay mr @andy-shi88  fixed

2017-10-19 03:53 UTC, andy-shi88 approved these changes
cool @aditiapratama1231

2017-10-19 03:53 UTC, andy-shi88 commented
I'll merge this along with the email confirmation message feature, let's put this here first @aditiapratama1231

2017-10-19 10:49 UTC, closed without merging